# Generated by Django 4.2.1 on 2023-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('share_price', models.FloatField()),
                ('currency', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
