# Generated by Django 4.2.1 on 2023-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_model',
            name='currency',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company_model',
            name='share_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
